[package]
name = "slsf"
version = "0.1.0"
edition = "2021"
authors = ["hz-xiaxz hzxiaxz@gmail.com"]
license = "MIT"

[features]
default = ["carlo-mc"]
carlo-mc = ["dep:carlo-mc"]
profile-stats = []

[dependencies]
carlo-mc = { git = "https://github.com/hz-xiaxz/carlo-mc.git", rev = "3547ec9ca25e98f1d45225d9008e03023aab6cc2", optional = true }
clap = { version = "4", features = ["derive"] }
hdf5-pure = "0.21"
rand = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
sleef = "0.3.3"

[dev-dependencies]
approx = "0.5"

[profile.profiling]
inherits = "release"
debug = true
strip = false
